# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c3a25c10424c98137cfe252b3c63ebf6cf85a5246ad7e52ec87e248e90d8f1920303cd61ec5cfd078311f9bdacfd0c790a3b1b6ccc760b08e052e15b7117643a

test:
  secret_key_base: fdf73013802e7cd2d96919ec049d85c8deed1cc8540722d433d19b03d7f533cc91eea1339280a6b01b94fa5dfd8ca39dfc0f29d9bc2e7f38b7972934aac9724c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
